# fly.toml file generated for lnbits on 2022-08-18T21:34:24-06:00

app = "lnbits"
kill_signal = "SIGINT"
kill_timeout = 30

[mounts]
source="lnbits_data"
destination="/data"

[env]
  HOST="lnbits.fly.dev"
  PORT=5000
  LNBITS_ALLOWED_USERS=""
  LNBITS_ADMIN_USERS=""
  LNBITS_ADMIN_EXTENSIONS="ngrok"
  LNBITS_DEFAULT_WALLET_NAME="LNbits wallet"
  LNBITS_AD_SPACE=""
  LNBITS_DISABLED_EXTENSIONS="amilk"
  LNBITS_DATA_FOLDER="/data"
  LNBITS_FORCE_HTTPS=true
  LNBITS_SERVICE_FEE="0.0"
  LNBITS_SITE_TITLE="Bitcoin Jungle"
  LNBITS_SITE_TAGLINE="free and open-source lightning wallet"
  LNBITS_SITE_DESCRIPTION="Some description about your service, will display if title is not 'LNbits'"
  LNBITS_THEME_OPTIONS="classic, bitcoin, freedom, mint, autumn, monochrome, salvador, strike"
  LNBITS_CUSTOM_LOGO="https://storage.googleapis.com/bitcoin-jungle-branding/logo/pwa/512.png"
  LNBITS_BACKEND_WALLET_CLASS="LndRestWallet"
  LND_REST_ENDPOINT="https://bitcoin-jungle-lnbits.m.voltageapp.io:8080"
  STRIKE_API_ENDPOINT="https://api.strike.me/"
  STRIKE_API_KEY="33ACE3001BBEB86C00B0E95FFCE2CA919C9BA0DB3666953399681FB369C4756D"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.http_checks]]
    grace_period = "60s"
